In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
vocab_size = 10000

In [4]:
one_hot_representation = [one_hot(sentence, vocab_size) for sentence in sent]

In [5]:
one_hot_representation

[[1647, 5827, 4594, 3259],
 [1647, 5827, 4594, 3746],
 [1647, 272, 4594, 363],
 [9332, 6662, 7417, 5076, 2456],
 [9332, 6662, 7417, 5076, 2312],
 [7313, 1647, 9474, 4594, 921],
 [4958, 6334, 3587, 5076]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
padded_sentences = pad_sequences(one_hot_representation, padding='pre', maxlen = max([len(sentence.split()) for sentence in sent]))
padded_sentences

array([[   0, 1647, 5827, 4594, 3259],
       [   0, 1647, 5827, 4594, 3746],
       [   0, 1647,  272, 4594,  363],
       [9332, 6662, 7417, 5076, 2456],
       [9332, 6662, 7417, 5076, 2312],
       [7313, 1647, 9474, 4594,  921],
       [   0, 4958, 6334, 3587, 5076]])

In [8]:
dim = 10

In [9]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=dim))
model.compile('adam', 'mse')

In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(padded_sentences)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step


array([[[-0.04189796,  0.04903508,  0.01200806, -0.01805384,
          0.00566582,  0.02599874,  0.0334678 , -0.01968013,
          0.04306395,  0.0160008 ],
        [ 0.04180033,  0.00529736,  0.006359  , -0.02413044,
         -0.02957466,  0.02850692,  0.0016461 , -0.00619382,
          0.04910468, -0.03009843],
        [-0.03841501, -0.0305404 , -0.03843517, -0.04064156,
          0.00289638,  0.01099779,  0.00940251, -0.01633696,
          0.03907545,  0.00485196],
        [-0.01065652, -0.04686711,  0.02351408,  0.02761397,
          0.04228559, -0.03288053,  0.03040839,  0.03887669,
         -0.01656196, -0.00971768],
        [-0.04969964, -0.02908483, -0.01670462, -0.04676771,
          0.02552829,  0.04401973, -0.02176762,  0.01237274,
         -0.0073606 ,  0.00665575]],

       [[-0.04189796,  0.04903508,  0.01200806, -0.01805384,
          0.00566582,  0.02599874,  0.0334678 , -0.01968013,
          0.04306395,  0.0160008 ],
        [ 0.04180033,  0.00529736,  0.006359  , -0

In [12]:
model.predict(padded_sentences)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[-0.04189796,  0.04903508,  0.01200806, -0.01805384,  0.00566582,
         0.02599874,  0.0334678 , -0.01968013,  0.04306395,  0.0160008 ],
       [ 0.04180033,  0.00529736,  0.006359  , -0.02413044, -0.02957466,
         0.02850692,  0.0016461 , -0.00619382,  0.04910468, -0.03009843],
       [-0.03841501, -0.0305404 , -0.03843517, -0.04064156,  0.00289638,
         0.01099779,  0.00940251, -0.01633696,  0.03907545,  0.00485196],
       [-0.01065652, -0.04686711,  0.02351408,  0.02761397,  0.04228559,
        -0.03288053,  0.03040839,  0.03887669, -0.01656196, -0.00971768],
       [-0.04969964, -0.02908483, -0.01670462, -0.04676771,  0.02552829,
         0.04401973, -0.02176762,  0.01237274, -0.0073606 ,  0.00665575]],
      dtype=float32)